# Generated by Django 4.1.3 on 2023-01-02 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('textfield', models.TextField()),
                ('slug', models.SlugField(default=None, max_length=250, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=500, null=True)),
                ('category', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
